mysql:
  build: mysql/
  ports:
    - "3306:3306"
  environment:
    DB_USER: docker
    DB_PASS: docker

redis:
  build: redis/
  ports:
    - "6379:6379"

postfix:
  build: postfix/
  ports:
    - "25:8025"

#rails:
#  build: rails/
#  ports:
#    - "3000:300"
#  volumes:
#    - .:/app
